# This file contains values from Cookiecutter

default_context:
  project_name: "qpython-daily"
  project_plug: "qpython_daily"
  project_description: "Awesome `qpython_daily` is a Python cli/package "
  organization: "qpython-daily"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.10
  github_name: "qpython_daily"
  email: "hello@qpython-daily.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
