[default]
DB_NAME = "mydb.db"
name = ""
key = "value"
a_boolean = false
number = 1234
a_float = 56.8
a_list = [1, 2, 3, 4]
a_dict = { hello = "world" }

  [a_dict.nested]
  other_level = "nested value

[development]
DB_PATH = "@format {env[HOME]}/{this.current_env}/{env[PROGRAM_NAME]}/{this.DB_NAME}"
name = "developer"

[production]
name = "admin"
