site_name: Fluent-QA Python文档模板项目
site_description: Documetation of Mkdocs site generation
site_author: Patrick
# Repository
repo_name: qdriven/fluent-md-doc-template
repo_url: https://github.com/qdriven/fluent-md-doc-template
edit_uri: "https://qdriven.github.io/fluent-md-doc-template/"

# Copyright
copyright: Copyright &copy; 2016 - 2021 FluentQA

nav:
- 主页: index.md
- 创建文档库:
  - "创建文档": 'create/create-doc-site/index.md'
  - "代办事项": 'create/create-doc-site/ToDoList.md'
- 贡献:
  - "如何贡献" : 'contribute/index.md'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: pink
    accent: pink
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.png'
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - toc.integrate
# theme: Cosmo
plugins:
  - search
  - minify:
        minify_html: true
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
