# This file contains values from Cookiecutter

default_context:
  project_name: "pyserver-simplify"
  project_plug: "pyserver_simplify"
  project_description: "Awesome `pyserver_simplify` is a Python cli/package "
  organization: "pyserver-simplify"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "qdriven"
  email: "hello@pyserver-simplify.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
