# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class NewTodo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewTodo - a model defined in OpenAPI

        id: The id of this NewTodo [Optional].
        title: The title of this NewTodo.
        description: The description of this NewTodo [Optional].
        created: The created of this NewTodo [Optional].
        due_date: The due_date of this NewTodo [Optional].
        complete: The complete of this NewTodo [Optional].
        author: The author of this NewTodo [Optional].
    """

    id: Optional[str] = None
    title: str
    description: Optional[str] = None
    created: Optional[datetime] = None
    due_date: Optional[datetime] = None
    complete: Optional[bool] = None
    author: Optional[str] = None

NewTodo.update_forward_refs()
