# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.new_todo import NewTodo


class Todo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Todo - a model defined in OpenAPI

        id: The id of this Todo.
        title: The title of this Todo.
        description: The description of this Todo [Optional].
        created: The created of this Todo [Optional].
        due_date: The due_date of this Todo [Optional].
        complete: The complete of this Todo [Optional].
        author: The author of this Todo [Optional].
    """

    id: str
    title: str
    description: Optional[str] = None
    created: Optional[datetime] = None
    due_date: Optional[datetime] = None
    complete: Optional[bool] = None
    author: Optional[str] = None

Todo.update_forward_refs()
