# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        family_name: The family_name of this User [Optional].
        given_name: The given_name of this User [Optional].
        name: The name of this User [Optional].
        preferred_username: The preferred_username of this User [Optional].
    """

    family_name: Optional[str] = None
    given_name: Optional[str] = None
    name: Optional[str] = None
    preferred_username: Optional[str] = None

User.update_forward_refs()
