# This file contains values from Cookiecutter

default_context:
  project_name: "fluentcli"
  project_plug: "fluentcli"
  project_description: "Awesome `fluentcli` is a Python cli/package "
  organization: "fluentcli"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "fluentcli"
  email: "hello@fluentcli.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "simple"
